#!/bin/bash
drive="/dev/"$(lsblk -S | awk {'print $1'} | sed -n '2 p')
#DRIVE
sfdisk $drive -f -w auto -X dos << EOF
,524288,L,*
;
EOF
mkfs.fat -F32 $drive"1"
mkfs.ext4 $drive"2"
mount $drive"2" /mnt
mkdir /mnt/boot
mount $drive"1" /mnt/boot
#BASE
basestrap /mnt base base-devel s6-base elogind-s6 linux-zen linux-firmware dhcpcd-s6 iwd-s6 openresolv grub os-prober efibootmgr connman-s6 connman-gtk vim git openssh
fstabgen -U /mnt >> /mnt/etc/fstab
modprobe efivarfs
cat configs/62 | artix-chroot /mnt /bin/bash
umount -R /mnt
reboot