#!/bin/bash
s6-rc-bundle-update -c /etc/s6/rc/compiled add default connmand
git clone https://github.com/soerenOsisa/configs /configs
cp /configs/.bashrc ~/.bashrc
cp /configs/aur /usr/local/bin/aur

#WINDOW
pacman --noconfirm -S xorg-xinit xorg-server terminus-font nvidia nvidia-utils xorg-xsetroot
nvidia-modprobe
git clone https://github.com/soerenOsisa/dwm /dwm
git clone https://github.com/soerenOsisa/dmenu /dmenu
git clone https://github.com/soerenOsisa/st /st
cd /dwm && make clean install && cd ..
cd /dmenu && make clean install && cd ..
cd /st && make clean install && cd ..
cp /configs/.xinitrc ~/.xinitrc
#BOOT
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
cp /configs/grub /etc/default/grub
cp /configs/boot.png /usr/local/boot.png
#USER
echo -e "six\nsix" | passwd
useradd -m -g wheel s
echo -e "six\nsix" | passwd s
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
#KBD&SYNC
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo 'LANG="en-US.UTF-8"' > /etc/locale.conf
echo "six" > /etc/hostname
ln -sf /usr/share/zoneinfo/posix/CET /etc/localtime
hwclock --systohc
kbd_mode -u
#PACKAGES
pacman --noconfirm -S htop
#FINISH
#s6-rc-bundle-update add default iwd dhcpcd
rm -r /configs
exit