#!/bin/bash
s6-rc-bundle-update -c /etc/s6/rc/compiled add default connmand
git clone https://github.com/soerenOsisa/configs /configs
cp /configs/.bashrc ~/.bashrc
cp /configs/aur /usr/local/bin/aur
echo "[[ -f ~/.profile ]] && . ~/.profile" > ~/.bash_profile
useradd paur
echo "paur ALL=(ALL) NOPASSWD: /usr/bin/makepkg" >> /etc/sudoers
#DESKTOP
pacman --noconfirm -S xorg nvidia nvidia-utils
nvidia-modprobe
/usr/local/bin/aur librewolf
/usr/local/bin/aur mailspring
git clone https://github.com/Axarva/dotfiles-2.0
cd dotfiles-2.0
chmod +x install-on-arch.sh
echo -e "3\nyes\ny\ny\ny\n2\ny\nN\ny\n2\ny\n" | ./install-on-arch.sh
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc
echo 'export PATH="$PATH:/home/s/bin"' >> ~/.zshrc
echo 'export PATH="$PATH:~/bin"' >> ~/.zshrc
xmonad --recompile
#sed -i "s/loginctl/s6-rc/g" ~/bin/powermenu.sh
cat /configs/.bashrc >> ~/.zprofile
echo "startx" >> ~/.zprofile
echo "exec xmonad" >> ~/.xinitrc
sed -i "s/9/12/g" ~/.config/alacritty.yml
#BOOT
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
cp /configs/grub /etc/default/grub
cp /configs/boot.png /usr/local/boot.png
update-grub
#USER
echo -e "six\nsix" | passwd
useradd -m -g wheel s
echo -e "six\nsix" | passwd s
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
#KBD&SYNC
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo 'LANG="en-US.UTF-8"' > /etc/locale.conf
echo "six" > /etc/hostname
ln -sf /usr/share/zoneinfo/posix/CET /etc/localtime
hwclock --systohc
kbd_mode -u
#PACKAGES

#FINISH
#s6-rc-bundle-update add default iwd dhcpcd
rm -r /configs
exit