#!/bin/bash
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
cp /configs/grub /etc/default/grub
cp /configs/boot.png /usr/local/boot.png
update-grub
sh /configs/s6user